#define dsyevd_ dsyevd
#define dsyev_ dsyev
#define dgemv_ dgemv
#define dgemm_ dgemm
#define dgesvd_ dgesvd
#define dgesdd_ dgesdd
#define dsyrk_ dsyrk
#define dpotrf_ dpotrf
#define dpocon_ dpocon
#define dpotri_ dpotri
#define dgetrf_ dgetrf
#define dgeevx_ dgeevx
#define ddot_ ddot
#define dnrm2_ dnrm2
#define dlansy_ dlansy
#define dgeev_ dgeev
#define sasum_ sasum
#define dasum_ dasum
#define snrm2_ snrm2
#define sdot_ sdot
#define sgemv_ sgemv
#define cgemv_ cgemv
#define zgemv_ zgemv
#define sgemm_ sgemm
#define cgemm_ cgemm
#define zgemm_ zgemm
#define ssyrk_ ssyrk
#define sgetrf_ sgetrf
#define cgetrf_ cgetrf
#define zgetrf_ zgetrf
#define sgeev_ sgeev
#define sgeevx_ sgeevx
#define ssyev_ ssyev
#define ssyevd_ ssyevd
#define spotrf_ spotrf
#define cpotrf_ cpotrf
#define zpotrf_ zpotrf
#define spotri_ spotri
#define cpotri_ cpotri
#define zpotri_ zpotri
#define sgesvd_ sgesvd
#define sgesv_ sgesv
#define dgesv_ dgesv
#define cgesv_ cgesv
#define zgesv_ zgesv
#define sposv_ sposv
#define dposv_ dposv
#define cposv_ cposv
#define zposv_ zposv
#define slansy_ slansy
#define dlansy_ dlansy
#define clansy_ clansy
#define zlansy_ zlansy
#define spocon_ spocon
#define sgesdd_ sgesdd